### ISSUE TITLE
export รายการคำขอใช้บริการเป็น csv แล้วภาษาไทยเพี้ยน

### ISSUE THREAD

**Issue by MzK0RE** [MzK0RE/trc-skw-iservice#1]
ในหน้าแสดงคำขอใช้บริการทั้งหมดของเจ้าหน้าที่ ถ้า export ข้อมูลโดยกดปุ่มด้านล่างสุดของตาราง จะทำให้ไฟล์ csv ที่ได้แสดงผลภาษาไทยเพี้ยน
![capture](https://cloud.githubusercontent.com/assets/9249682/5423626/ae4de976-82f9-11e4-8981-715bc8369df1.PNG)

**Comment by enividlived** [comment]
![presentmacroconvert](https://cloud.githubusercontent.com/assets/10202947/5699502/757ff5a6-9a5c-11e4-9239-c603b5816162.png)

ทำเป็นมาโคร ส่วนบุคคล โดยการเขียน vba macro และ form show เพื่อให้ผู้staff เลือกไฟล์ที่ต้องการ ให้แสดงภาษาไทยให้เรียบร้อย

ให้ใช้งานไปก่อนจนกว่าทาง source หรือ ส่วน UTF 8 ซึ่งเป็นรูปแบบภาษาสากลจะพัฒนาให้รองรับภาษาไทยที่ดีกว่านี้

**Comment by MzK0RE** [comment]
เวลาอ้างที่อยู่ไฟล์ csv ที่จะให้แปลง ตอนนี้ตัว macro ยังอ้างจาก "C:\Users\xxx\Downloads" ได้แค่อย่างเดียวถูกไหม? แล้วทำให้แบบเป็นเลือกไฟล์หรือไม่ก็ที่อยู่ไฟล์เองได้หรือเปล่า?

**Comment by enividlived** [comment]
คาดว่ามันจำเป็นนะ เพราะผู้ใช้ไม่สามารถเลือกตำแหน่งที่จะ export file ออกมาได้อยู่แล้วเป็น path "C:\Users\xxx\Downloads"  โดย auto อยู่แล้วดังนั้น ถ้าผู้ใช้จะเปลี่บยตำแหน่ง ไฟล์จึงเป็นตอนหลังจาก Convert ภาษาด้วย Macro แล้ว

**Comment by enividlived** [comment]
กำลังดำเนินการ เขียน VBA ให้ไฟล์นั้นสามารถ แก้ภาษาด้วยตัวแล้ว และไม่จำเป็นต้องเลือก ชื่อ file และ position 
แต่มีข้อกำจัดคือ ต้องเปลี่ยนโดยการเปิดจาก file นั้นๆ เท่านั้น

**Comment by MzK0RE** [comment]
เราเข้าใจแบบนี้ถูกหรือเปล่า หมายความว่าตัวมาโครที่แก้ใหม่ มันไม่ต้องกดเพื่อเลือกไฟล์แล้ว มันสามารถอ้างชื่อตัวเองแล้วรันมาโครแก้ภาษาได้เลย แต่ว่าจะต้องมาไล่คลิกทีละไฟล์แล้วกดรันเอง แบบนี้ถูกไหม? :confused:

**Comment by enividlived** [comment]
ถูกต้องตามนั้น ok?

**Comment by MzK0RE** [comment]
ok :thumbsup:

**Comment by enividlived** [comment]
![presentmacrolan](https://cloud.githubusercontent.com/assets/10202947/5798459/e90bf64e-9ff9-11e4-8531-9b99d32a58b9.png)

ใช้งานได้ในการกดเพียงครั้งเดียวแล้ว ขอปิด Topic ไปก่อน แล้วได้ขอสรุปเรื่อง ภาษาในการประชุม
