### ISSUE TITLE
เปลี่ยนโลโก้ staff panel กับ admin panel

### ISSUE THREAD

**Issue by MzK0RE** [MzK0RE/trc-skw-iservice#17]
เปลี่ยนโลโก้ส่วนของ staff ให้เป็นแบบเดียวกับของ user
![capture](https://cloud.githubusercontent.com/assets/9249682/5625206/f6c9364e-95a8-11e4-8901-038b526b3bec.PNG)
![capture](https://cloud.githubusercontent.com/assets/9249682/5698210/0e965900-9a3b-11e4-9eaa-6e78ac78c00e.PNG)

**Comment by enividlived** [comment]
![logopresent](https://cloud.githubusercontent.com/assets/10202947/5714617/0877db3e-9afe-11e4-886f-266a5caf8656.png)

![logologinpresent](https://cloud.githubusercontent.com/assets/10202947/5714633/57389434-9afe-11e4-99ea-91edf2d31ecf.png)
