### ISSUE TITLE
export คำขอใช้บริการเป็น PDF แล้วภาษาไทยไม่แสดงผล

### ISSUE THREAD

**Issue by MzK0RE** [MzK0RE/trc-skw-iservice#2]
ถ้าสั่งให้พิมพ์คำขอใช้บริการเป็น pdf จะทำให้ไฟล์ที่ได้แสดงผลภาษาไทยเพี้ยนในส่วนของคำอธิบายด้านบน
แต่ถ้าใช้โปรแกรมแก้ไขไฟล์ pdf อย่าง acrobat แล้วไปเปลี่ยน font ใหม่เป็น microsoft sans serif ก็จะเห็นภาษาไทยตามปกติ
![capture](https://cloud.githubusercontent.com/assets/9249682/5423649/7e007da0-82fa-11e4-9bab-2ab12cbc53d5.PNG)

**Comment by enividlived** [comment]
![presentpdf](https://cloud.githubusercontent.com/assets/10202947/5717978/1735be7e-9b3b-11e4-9edb-493f457519c5.png)


ดำเนินการแล้ว
