### ISSUE TITLE
ถาม-ตอบ เปลี่ยนชื่อใหม่

### ISSUE THREAD

**Issue by enividlived** [MzK0RE/trc-skw-iservice#24]
เนื่องจากหัวข้อนี้คาดว่า จะเป็นส่วนที่จะให้ความรู้แก่ผู้ใช้ เพียงด้านเดียวไม่มีให้สร้างคำถามจึงคิดว่าเปลี่ยนชื่อ จาก"ถาม-ตอบ"เป็น "องค์ความรู้" ดีไหม

**Comment by MzK0RE** [comment]
ตอนแรกก็ตั้งชื่อให้ว่า "ฐานความรู้" นั่นแหละ แต่คิดว่าอาจจะสื่อความได้ไม่ดีเท่าไหร่ เลยใช้คำว่า "ถาม-ตอบ" แทน

**Comment by enividlived** [comment]
ok ถ้ายังไม่ศัพท์ที่ดีพอใช้ ถามตอบ ไปก่อนแล้วกัน
