### ISSUE TITLE
Update from osTicket-v1.9.5

### ISSUE THREAD

**Issue by enividlived** [MzK0RE/trc-skw-iservice#27]
*Add support for organization vars in templates (%{ticket.user.organization...}) (#1561)

*Canned responses feature can now be disabled (#1562)

*Drop link redirection through l.php (#1640)

*Use unified file download script (#1641). Links can now be shared with external users and accessed without authenticating.   (ไม่ดำเนินการจนกว่าจะมีการลงความเห็นว่าจำเป็นต้องใช้จริงๆ)

*Ticket filters support matching and banning based on the Reply-To user information (#1645)

**Comment by enividlived** [comment]
*Add support for organization vars in templates (%{ticket.user.organization...}) (#1561)
เพิ่ม Function asVar ให้ใช้ตัวแปร vars โดยมีการ Return ค่า เป็น String ออกมาได้
เพิ่ม Function getVar สามารถรับค่า vars ได้
ดำเนินการแล้ว

**Comment by enividlived** [comment]
*Canned responses feature can now be disabled (#1562)
ดำเนินการแล้ว แต่ยังต้องมีส่วนเพิ่มเติม แต่เป็น Function ที่ยังไม่มีความจำเป็นจึง รอ update ภายหลัง

**Comment by MzK0RE** [comment]
merge ไปละ ถ้ามีอะไรจะเพิ่มก็สร้าง commit ใหม่ละกัน

**Comment by enividlived** [comment]
*Drop link redirection through l.php (#1640)
ตัด Code ส่วน I.php ทิ้ง
ดำเนินการแล้ว 
ทำการแก้ Code ในส่วน
include/class.format.php
include/class.thread.php
l.php  (ล้างทิ้ง)
scp/l.php  (ล้างทิ้ง)

**Comment by enividlived** [comment]
*Use unified file download script (#1641). Links can now be shared with external users and accessed without authenticating.
เป็นส่วนที่ให้ผู้ใช้ภายนอกสามารถ download file ได้ โดยไม่ได้ต้องขออนุญาต
(ไม่ดำเนินการจนกว่าจะมีการลงความเห็นว่าจำเป็นต้องใช้จริงๆ)

**Comment by MzK0RE** [comment]
รู้สึกเหมือนมันจะเริ่มเยอะขึ้นแล้วนะ เราว่าสร้าง commit แยกแต่ละอัพเดทไปเลยดีกว่า แล้วค่อยกำหนดป้ายชื่อกำกับเอา :+1:

**Comment by enividlived** [comment]
*Ticket filters support matching and banning based on the Reply-To user information (#1645)
ป้องกันการเกิด loop จากการ filter และตอบรับโดยการ filter ชื่อและที่อยู่
แก้ไข Code ส่วน
include/class.filter.php
include/class.ticket.php
ดำเนินการแล้ว ปิดงาน
Enhancements สุดท้ายของ v1.9.5
