### ISSUE TITLE
ข้อความล้นตรง help topic ตอน report pdf

### ISSUE THREAD

**Issue by MzK0RE** [MzK0RE/trc-skw-iservice#33]
น่าจะเป็นเพราะชื่อบริการมันมีหัวข้อหลัก "ICT / xxx" พ่วงมาด้วย เลยทำให้ข้อความล้นออกมา เดี๋ยวค่อยหาวิธีแก้อีกที 
![capture](https://cloud.githubusercontent.com/assets/9249682/5914567/9a8b0848-a62a-11e4-87d0-881c7ffef850.PNG)

**Comment by enividlived** [comment]
![bugpdf](https://cloud.githubusercontent.com/assets/10202947/6077055/7f388cf0-ae1d-11e4-894d-d4a60a22104d.png)

ตัดข้อความ Help Topic นำตัวเลข ชื่อ แผนก / ออก
นำหัวข้อ "ข้อมูลเพิ่มเติมทั่วไป" ออกเนื่องจากไม่จำเป็นต้องใช้
