### ISSUE TITLE
ตัด combo box ออกจาก iservice

### ISSUE THREAD

**Issue by MzK0RE** [MzK0RE/trc-skw-iservice#45]
หลังจากแยกระบบออกไปแต่ละแผนกแล้ว ตัว combo box ก็คงไม่จำเป็น ฝาก @enividlived จัดการด้วยละกัน

**Comment by enividlived** [comment]
สถานะ รอ การประชุม

**Comment by MzK0RE** [comment]
สรุป ไม่ต้องแยกระบบแต่ให้แยกแค่เลขที่คำขอออกจากกัน ซึ่งตัว iservice สามารถทำได้อยู่แล้ว
